Make layers the only way to provision a server when using env variables

diff --git a/jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon b/jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
--- a/jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
+++ b/jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
@@ -1,5 +1,4 @@
 GALLEON_GENERIC_LAYERS_DEFINITION="$JBOSS_CONTAINER_WILDFLY_S2I_LEGACY_GALLEON_MODULE"/provisioning/generic_layers
-GALLEON_DEFAULT_DEFINITION="$JBOSS_CONTAINER_WILDFLY_S2I_LEGACY_GALLEON_MODULE"/provisioning/default_config
 GALLEON_GENERIC_PROVISIONING_DEFINITION="$JBOSS_CONTAINER_WILDFLY_S2I_LEGACY_GALLEON_MODULE"/provisioning/generic_provisioning
 
 function galleon_patch_generic_config() {
@@ -31,24 +30,6 @@ function galleon_patch_generic_config() {
        sed -i "s|<!-- ##GALLEON_FEATURE_PACKS## -->|${featurepacks}|" $GALLEON_GENERIC_LAYERS_DEFINITION/pom.xml
      fi
    fi
-}
-
-function galleon_patch_default_config() {
-  # default config, use the latest fp default configs.
-  feature_packs_content=
-  fps_array=()
-  for fp in $(echo "${GALLEON_PROVISION_FEATURE_PACKS}" | sed "s/,/ /g"); do
-    fps_array+=($fp)
-  done
-  lastIndex=$((${#fps_array[@]} -1))
-  for index in "${!fps_array[@]}"; do
-    inherit_configs="false";
-    if [ $index == $lastIndex ]; then
-      inherit_configs="true";
-    fi
-    feature_packs_content="$feature_packs_content<feature-pack><location>${fps_array[$index]}</location><inherit-packages>true</inherit-packages><inherit-configs>$inherit_configs</inherit-configs></feature-pack>"
-  done
-  sed -i "s|<!-- ##GALLEON_FEATURE_PACKS## -->|${feature_packs_content}|" $GALLEON_DEFAULT_DEFINITION/pom.xml
 }
 
 function galleon_init_mvn_env() {
@@ -155,46 +136,38 @@ function galleon_provision_server() {
         log_warning "Galleon provisioning of layers overrides Galleon provisioning.xml located in $GALLEON_LOCAL_PROVISIONING"
       fi
     else
-      if [ -n "$GALLEON_PROVISION_FEATURE_PACKS" ]; then
-        galleon_patch_default_config
-        GALLEON_DESCRIPTION_LOCATION="$GALLEON_DEFAULT_DEFINITION"
-        if [ -n "${GALLEON_USE_LOCAL_FILE}" ] && [ -f $GALLEON_LOCAL_PROVISIONING/provisioning.xml ]; then
-          log_warning "Galleon provisioning of default config overrides Galleon provisioning.xml located in $GALLEON_LOCAL_PROVISIONING"
-        fi
+      if [ -n "${GALLEON_USE_LOCAL_FILE}" ] && [ -f "$GALLEON_LOCAL_PROVISIONING/provisioning.xml" ]; then
+        log_info "Provisioning server with Galleon description in $GALLEON_LOCAL_PROVISIONING"
+        mkdir -p "$GALLEON_GENERIC_PROVISIONING_DEFINITION"/galleon
+        cp "$GALLEON_LOCAL_PROVISIONING/provisioning.xml" "$GALLEON_GENERIC_PROVISIONING_DEFINITION"/galleon
+        GALLEON_DESCRIPTION_LOCATION="$GALLEON_GENERIC_PROVISIONING_DEFINITION"
       else
-        if [ -n "${GALLEON_USE_LOCAL_FILE}" ] && [ -f "$GALLEON_LOCAL_PROVISIONING/provisioning.xml" ]; then
-          log_info "Provisioning server with Galleon description in $GALLEON_LOCAL_PROVISIONING"
-          mkdir -p "$GALLEON_GENERIC_PROVISIONING_DEFINITION"/galleon
-          cp "$GALLEON_LOCAL_PROVISIONING/provisioning.xml" "$GALLEON_GENERIC_PROVISIONING_DEFINITION"/galleon
-          GALLEON_DESCRIPTION_LOCATION="$GALLEON_GENERIC_PROVISIONING_DEFINITION"
-        else
-          log_error "No provisioning.xml file exists in $GALLEON_LOCAL_PROVISIONING, invalid galleon configuration."
-          exit 1
-         fi
+        log_error "No provisioning.xml file exists in $GALLEON_LOCAL_PROVISIONING, invalid galleon configuration."
+        exit 1
       fi
     fi
       
-      if [ -f "$GALLEON_DESCRIPTION_LOCATION/pom.xml" ]; then
-          log_info "Provisioning WildFly server..."
-          maven_build "$GALLEON_DESCRIPTION_LOCATION" package
+    if [ -f "$GALLEON_DESCRIPTION_LOCATION/pom.xml" ]; then
+      log_info "Provisioning WildFly server..."
+      maven_build "$GALLEON_DESCRIPTION_LOCATION" package
 
-          ERR=$?
-          if [ $ERR -ne 0 ]; then
-            log_error "Aborting due to error code $ERR from mvn install"
-            exit $ERR
-          fi
-          targetDir=$GALLEON_DESCRIPTION_LOCATION/target/server
-          if [ -d $targetDir ]; then
-            galleon_replace_server $targetDir
-            rm -rf $targetDir
-          else
-            log_error "Error, no server provisioned in $targetDir"
-            exit 1
-          fi
-      else
-          log_error "Not a valid galleon description $GALLEON_DESCRIPTION_LOCATION exiting"
-          exit 1
+      ERR=$?
+      if [ $ERR -ne 0 ]; then
+        log_error "Aborting due to error code $ERR from mvn install"
+        exit $ERR
       fi
+      targetDir=$GALLEON_DESCRIPTION_LOCATION/target/server
+      if [ -d $targetDir ]; then
+        galleon_replace_server $targetDir
+        rm -rf $targetDir
+      else
+        log_error "Error, no server provisioned in $targetDir"
+        exit 1
+      fi
+    else
+      log_error "Not a valid galleon description $GALLEON_DESCRIPTION_LOCATION exiting"
+      exit 1
+    fi
     galleon_reset_mvn_env
 }
 
